### ISSUE TITLE
Using topictuner with a pretrained model

### ISSUE THREAD

**Issue by chrislalk** [drob-xx/TopicTuner#4] opened 2022-12-12 23:25 UTC
I have been playing with TopicTuner and wanted to use the [gbert large](https://huggingface.co/deepset/gbert-large) language model from hugging face. Unfortunately, I got an error message: `'FeatureExtractionPipeline' object has no attribute 'encode'` 

My code is: 

```

from transformers.pipelines import pipeline
gbert = pipeline("feature-extraction", model="deepset/gbert-large")
...
tmt = TMT(embedding_model = gbert)
tmt.createEmbeddings(docs=docs)

```

However, using a sentence-transformer model worked out well. Is the issue caused by using hugging face? And do you have a suggestion for a workaround?

Thanks a lot!

**Comment by drob-xx** [comment] 2022-12-13 06:01
Interesting. You should be able to simply generate the embeddings and then assign via `embeddings=yourEmbeddings` in the constructor or after instantiation with `yourTMTInstance.embeddings=yourEmbeddings` you can then skip createEmbeddings and just carry on. I'll take a look at what's going on but it'll probably be a day or two. I'd love to get your feedback at some point.

**Comment by drob-xx** [comment] 2023-01-11 21:01
@chrislalk Sorry it took so long to get back to this. The problem is that TMT expects the `embedding_model `to have an `encode` method which will return the embeddings to be clustered (after they are reduced). In this version, as I mentioned - you can generate your embeddings however you want and pass them in via `TMT.embeddings=`. In the next version (imminent) you can do that or if you don't want to reduce embeddings you can pass in `TMT.target_vectors`

**Comment by drob-xx** [comment] 2023-01-12 18:45
Closing this as the issue is currently out of scope.

**Closed** 2023-01-12 18:45 UTC
